version: '3'

services:

  db:
    ports:
      - "3307:3306"
    networks:
      - internal
    labels:
      - traefik.enable=false

  php:
    image: registry.mmsrv.nl/topquote-php:latest
    networks:
      - internal
    labels:
      - traefik.enable=false

  nginx:
    image: registry.mmsrv.nl/topquote-nginx:latest
    networks:
      - internal
      - web
    labels:
      - traefik.enable=true
      # - traefik.port=80
      - traefik.http.routers.topquote.rule=Host(`topquote.nl`, `www.topquote.nl`)
      - traefik.http.routers.topquote.middlewares=www2nonwww@file
      - traefik.http.routers.topquote.entrypoints=websecure
      - traefik.http.routers.topquote.tls=true
      - traefik.http.routers.topquote.tls.certresolver=letsencrypt

      - traefik.http.routers.topquote2.rule=Host(`topquote.nl`, `www.topquote.nl`)
      - traefik.http.routers.topquote2.middlewares=redirect-https@file
      - traefik.http.routers.topquote2.entrypoints=web

networks:
  web:
    external: true
  internal:
    external: false
