version: '3'

services:

  traefik:
    image: "traefik:2.4"
    container_name: topquote-traefik
    command:
      - "--log.level=DEBUG"
      - "--configFile=/config/traefik.yml"
    ports:
      - "80:80"
    #      - "443:443"
    volumes:
      - "./traefik.dev.yml:/config/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    ports:
      - "3306:3306"
      
  php:
    build:
      context: app
      dockerfile: Dockerfile

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - topquote.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.topquote.rule=Host(`topquote.local`)
      - traefik.http.routers.topquote.entrypoints=web

  compiler:
    image: topquote-compiler 
    container_name: topquote-compiler
    build:
      context: .
      dockerfile: ./compiler/Dockerfile
    volumes:
      - ./app:/project/app
      - ./src:/project/src
      - ./webpack:/project/webpack
      - ./webpack.config.js:/project/webpack.config.js
      - ./package.json:/project/package.json
      - ./package-lock.json:/project/package-lock.json

