version: '3'

services:

  db:
    ports:
      - "3306:3306"
      
  php:
    build:
      context: app
      dockerfile: Dockerfile

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - topquote.local
    ports:
      - "80:80"

  # compiler:
  #   image: topquote-compiler 
  #   container_name: topquote-compiler
  #   build:
  #     context: .
  #     dockerfile: ./compiler/Dockerfile
  #   volumes:
  #     - ./app:/project/app
  #     - ./src:/project/src
  #     - ./webpack:/project/webpack
  #     - ./webpack.config.js:/project/webpack.config.js
  #     - ./package.json:/project/package.json
  #     - ./package-lock.json:/project/package-lock.json

