version: '3'

services:

  db:
    image: mariadb:10.7.1
    container_name: topquote-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./mount/db:/var/lib/mysql
      - ./import/topquote-nl4.sql:/docker-entrypoint-initdb.d/00-init.sql

  php:
    container_name: topquote-php
    restart: always
    volumes:
      - './app:/var/www'
      - './mount/cache:/var/www/cache'
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    container_name: topquote-nginx
    restart: always
    volumes_from:
      - php
    depends_on:
      - php
    env_file:
      - .env
