version: '3'

services:

  db:
    image: mariadb:10.7.1
    container_name: topquote-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql
      - ./import:/docker-entrypoint-initdb.d

  php:
    container_name: topquote-php
    env_file:
      - .env
    volumes:
      - ./app:/var/www
      - ./mount/cache:/var/www/cache
      - ./mount/template-cache:/var/www/templates/cache
    depends_on:
      - db

  nginx:
    container_name: topquote-nginx
    volumes_from:
      - php
    depends_on:
      - php
    env_file:
      - .env

volumes:
  dbdata: