version: '3'

services:

  db:
    image: mariadb:10.7.1
    container_name: topquote-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - ./dockerfiles/db/data:/var/lib/mysql 
      - ./dockerfiles/db/topquote-nl4.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - internal
    labels:
      - traefik.enable=false

  cache:
    image: redis:7.0-rc
    container_name: topquote-cache
    restart: always
    ports:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    depends_on:
      - db
    networks:
      - internal
    labels:
      - traefik.enable=false

  php:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    volumes:
      - './app:/var/www'
      # - './.env:/var/.env'
    container_name: topquote-php
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal
    labels:
      - traefik.enable=false

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    container_name: topquote-nginx
    restart: on-failure
    volumes:
      - './app:/var/www'
    depends_on:
      - php
    env_file:
      - .env
    networks:
      - internal
      - web
    labels:
      - traefik.enable=true
      # - traefik.port=80
      - traefik.http.routers.topquote.rule=Host(`topquote.nl`, `www.topquote.nl`)
      - traefik.http.routers.topquote.middlewares=www2nonwww@file
      - traefik.http.routers.topquote.entrypoints=websecure
      - traefik.http.routers.topquote.tls=true
      - traefik.http.routers.topquote.tls.certresolver=letsencrypt

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: topquote-phpmyadmin
  #   environment:
  #     - PMA_ARB ITRARY=1
  #     - PMA_HOST=${DB_HOST}
  #     - PMA_PORT=3306
  #     - PMA_ABSOLUTE_URI=pma.topquote.nl
  #     - UPLOAD_LIMIT=400M
  #   # ports:
  #     # - "${PHPMYADMIN_PORT}:80"
  #   links:
  #     - db
  #   networks:
  #     - internal
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.pma.rule=Host(`pma.topquote.nl`)
  #     - traefik.http.routers.pma.entrypoints=websecure
  #     - traefik.http.routers.pma.tls=true
  #     - traefik.http.routers.pma.tls.certresolver=letsencrypt

volumes:
  cache:
    driver: local

networks:
  web:
    external: true
  internal:
    external: false
