version: '3'

services:

  traefik:
    image: "traefik:2.4"
    container_name: topquote-traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--configFile=/config/traefik.yml"
    ports:
      - "80:80"
    #      - "443:443"
    volumes:
      - "./traefik.dev.yml:/config/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.local`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api@internal"

  db:
    ports:
      - "3307:3306"
  php:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - './app:/var/www'
      - './mount/cache:/var/www/cache'

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - topquote.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.topquote.rule=Host(`topquote.local`)
      - traefik.http.routers.topquote.entrypoints=web

  cache:
    image: redis:7.0-rc
    container_name: topquote-cache
    restart: always
    ports:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    depends_on:
      - db
    # networks:
    #   - internal
    # labels:
    #   - traefik.enable=false

volumes:
  cache:
    driver: local

