version: '3'

services:

  db:
    image: mariadb:10.7.1
    container_name: topquote-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./dockerfiles/db/data:/var/lib/mysql 
      - ./dockerfiles/db/topquote-nl4.sql:/docker-entrypoint-initdb.d/db.sql

  cache:
    image: redis:7.0-rc
    container_name: topquote-cache
    restart: always
    ports:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    depends_on:
      - db

  php:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    volumes:
      - './app:/var/www'
      - './env:/var/.env'
    container_name: topquote-php
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    container_name: topquote-nginx
    restart: on-failure
    volumes:
      - './app:/var/www'
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: topquote-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=${SITE_URL}/pma/
      - UPLOAD_LIMIT=400M
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
      - db

volumes:
  cache:
    driver: local
