entryPoints:
  web:
    address: :80
  websecure:
    address: :443

api:
  insecure: false
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /config/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: mail@josfaber.nl
      storage: /letsencrypt/acme.json
